### ISSUE TITLE
Missing Linbo-Vars

### ISSUE THREAD

**Issue by hhagenowpaul** [netzint/linuxmuster-cachingserver-satellite#9]
On caching-server the following is missing in /usr/lib/linuxmuster/constants.py:
```
LINBOSYSDIR = SYSDIR + '/linbo'
LINBOVARDIR = VARDIR + '/linbo'

```

**Comment by hermanntoast** [comment]
New version of constants.py was added in https://github.com/netzint/linuxmuster-cachingserver-linbo7/commit/444ecb3a879ebff1b6de2464d320e1308a219fe2
